### ISSUE TITLE
Criar configuração do banco de dados no projeto

### ISSUE THREAD

**Issue by FelipeNathan** [fn-devteam/campservice#2]
Crie um arquivo chamado `docker-compose.yaml` (talvez precise instalar o componente docker-compose no linux):

Exemplo de configuração:
```yaml
version: '3.3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - "3306:3306"
```
